package entidades;
// Generated 11-30-2016 01:02:38 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Photo generated by hbm2java
 */
public class Photo implements java.io.Serializable {

    private Integer photoId;
    private User user;
    private String title;
    private byte[] photoFile;
    private String descripcion;
    private Date createdDate;
    private Set<Comment> comments = new HashSet<Comment>(0);

    public Photo() {
    }

    //Constructor utilizado para mostrar listas
    public Photo(User user, String title, String descripcion, Date createdDate) {
        this.user = user;
        this.title = title;
        this.descripcion = descripcion;
        this.createdDate = createdDate;
    }

    public Photo(User user, String title, String descripcion, byte[] photoFile) {
        this.user=user;
        this.title = title;
        this.descripcion = descripcion;
        this.photoFile = photoFile;
        this.createdDate= new Date();
    }

    public Photo(String title, byte[] photoFile, String descripcion, Date createdDate) {
        this.title = title;
        this.photoFile = photoFile;
        this.descripcion = descripcion;
        this.createdDate = createdDate;
    }

    public Photo(User user, String title, byte[] photoFile, String descripcion, Date createdDate, Set<Comment> comments) {
        this.user = user;
        this.title = title;
        this.photoFile = photoFile;
        this.descripcion = descripcion;
        this.createdDate = createdDate;
        this.comments = comments;
    }

    public Integer getPhotoId() {
        return this.photoId;
    }

    public void setPhotoId(Integer photoId) {
        this.photoId = photoId;
    }

    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public byte[] getPhotoFile() {
        return this.photoFile;
    }

    public void setPhotoFile(byte[] photoFile) {
        this.photoFile = photoFile;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Date getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    public Set<Comment> getComments() {
        return this.comments;
    }

    public void setComments(Set<Comment> comments) {
        this.comments = comments;
    }

}
